export const TODO_ACTIONS={
    ADD_TODO: 'ADD',
    EDIT_TODO: 'EDIT_TODO',
    REMOVE_TODO : 'REMOVE_TODO',
    COMPLETE: 'COMPLETE_TODO',
    CLEAR_TODO:'CLEARE_TODO',
    SAVE_CHANGES :'SAVE_CHANGES',
    TEST:'test'
}